name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ vars.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v5

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: 📦 Install Poetry
        run: pipx install poetry

      - name: 🔧 Install dependencies
        run: poetry install

      - name: 🧪 Run tests
        run: poetry test
